Repository Cherish-Gift/back-spring, pull requests merged in 2023-05, with the labels that each got.

#126 Feature/120 search sort
  src/main/java/cherish/backend/item/constant/ItemSortConstants.java
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemSearchCondition.java
  src/main/java/cherish/backend/item/dto/ItemSearchResponseDto.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
Labels: feature

#131 Bug/129 add img url to monthly api
  src/main/java/cherish/backend/board/dto/MonthlyCurationResponseDto.java
  src/main/java/cherish/backend/board/dto/query/MonthlyCurationQueryDto.java
  src/main/java/cherish/backend/board/repository/MonthlyBoardRepository.java
  src/test/java/cherish/backend/item/service/ItemSearchServiceTest.java
Labels: bug

#132 add: JWT auth정보 없을 시 401상태 만들어주는 entry point 추가
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
Labels: bug

#134 add: 월별 큐레이션 API에 item id 필드 추가
  src/main/java/cherish/backend/board/dto/MonthlyCurationResponseDto.java
  src/main/java/cherish/backend/board/dto/query/MonthlyCurationQueryDto.java
  src/main/java/cherish/backend/board/repository/MonthlyBoardRepository.java
Labels: bug

#141 [refactor] 중복 banner imgUrl insert 방지 및 PageResponse로 변경
  src/main/java/cherish/backend/board/repository/MonthlyBoardRepository.java
  src/main/java/cherish/backend/board/repository/MonthlyBoardRepositoryCustom.java
  src/main/java/cherish/backend/board/service/MonthlyBoardService.java
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/RecommendItemQueryDto.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/java/cherish/backend/item/repository/RecommendItemRepository.java
  src/main/java/cherish/backend/item/service/ItemService.java
  src/main/java/cherish/backend/item/service/RecommendItemService.java
  src/main/resources/application.yml
  src/test/java/cherish/backend/category/model/CategoryTest.java
  src/test/java/cherish/backend/item/controller/ItemSearchControllerTest.java
  src/test/java/cherish/backend/item/service/ItemSearchServiceTest.java
Labels: refactor

#143 Refactor/139 send email async
  src/main/java/cherish/backend/common/config/AsyncConfig.java
  src/main/java/cherish/backend/common/constant/CommonConstants.java
  src/main/java/cherish/backend/member/email/service/EmailService.java
Labels: refactor

#149 Refactor/148 fix request response log filter
  src/main/java/cherish/backend/board/constant/.gitkeep
  src/main/java/cherish/backend/category/constant/.gitkeep
  src/main/java/cherish/backend/category/controller/.gitkeep
  src/main/java/cherish/backend/category/dto/.gitkeep
  src/main/java/cherish/backend/category/service/.gitkeep
  src/main/java/cherish/backend/common/filter/RequestResponseLoggingFilter.java
  src/main/java/cherish/backend/common/repository/.gitkeep
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: refactor

#150 [fix] item search request param emotionName(마음) add
  src/main/java/cherish/backend/item/dto/ItemSearchCondition.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/resources/application.yml
Labels: search, refactor

#152 fix: get item like orderby추가
  src/main/java/cherish/backend/item/repository/ItemLikeRepositoryImpl.java
Labels: refactor

#154 [refactor] itemLike 중복으로 여러번 DB에 저장되는 이슈
  src/main/java/cherish/backend/item/constant/ItemConstant.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepository.java
  src/main/java/cherish/backend/item/repository/RecommendItemRepository.java
  src/main/java/cherish/backend/item/service/ItemLikeService.java
  src/main/java/cherish/backend/item/service/RecommendItemService.java
  src/test/java/cherish/backend/item/controller/ItemSearchControllerTest.java
Labels: refactor

#155 keyword 조건 추가
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
Labels: refactor
