Repository Cherish-Gift/back-spring, pull requests merged in 2023-04, with the labels that each got.

#57 feature/ItemLike 관련 기능제작
  src/main/java/cherish/backend/item/constant/ItemConstant.java
  src/main/java/cherish/backend/item/controller/.gitkeep
  src/main/java/cherish/backend/item/controller/ItemLikeController.java
  src/main/java/cherish/backend/item/dto/ItemLikeDto.java
  src/main/java/cherish/backend/item/dto/ItemLikeRequest.java
  src/main/java/cherish/backend/item/model/ItemLike.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepository.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepositoryImpl.java
  src/main/java/cherish/backend/item/service/.gitkeep
  src/main/java/cherish/backend/item/service/ItemLikeService.java
  src/test/java/cherish/backend/item/model/ItemLikeTest.java
  src/test/java/cherish/backend/item/service/ItemLikeServiceTest.java
  src/test/java/cherish/backend/member/MemberTest.java
Labels: feature

#69 HttpRequestMethodNotSupportedException handler 추가
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
Labels: feature

#67 Bug/#65 클라이언트 JSON 바인딩 에러 해결을 위한 @NoArgsConstructor 추가
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/item/controller/ItemLikeController.java
  src/main/java/cherish/backend/item/dto/ItemLikeRequest.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
  src/main/java/cherish/backend/member/dto/ChangeInfoRequest.java
  src/main/java/cherish/backend/member/dto/ChangePwdRequest.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/dto/MemberLoginRequestDto.java
  src/main/java/cherish/backend/member/dto/email/EmailCodeValidationRequest.java
  src/main/java/cherish/backend/member/dto/email/EmailRequest.java
Labels: bug

#81 구글 smtp 사용한 EmailService 추가
  src/main/java/cherish/backend/member/email/service/AwsEmailService.java
  src/main/java/cherish/backend/member/email/service/EmailService.java
  src/main/java/cherish/backend/member/email/service/GoogleEmailService.java
  src/main/java/cherish/backend/member/email/util/EmailCodeGenerator.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/cherish/backend/member/email/AwsEmailServiceTest.java
Labels: feature

#79 Feature/75 add token refresh api
  src/main/java/cherish/backend/auth/jwt/JwtConfig.java
  src/main/java/cherish/backend/auth/jwt/JwtExceptionFilter.java
  src/main/java/cherish/backend/auth/jwt/JwtProperties.java
  src/main/java/cherish/backend/auth/jwt/JwtTokenProvider.java
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/common/config/WebMvcConfig.java
  src/main/java/cherish/backend/common/controller/.gitkeep
  src/main/java/cherish/backend/common/controller/TokenRefreshController.java
  src/main/java/cherish/backend/common/dto/RefreshTokenRequestDto.java
  src/main/java/cherish/backend/common/exception/DurationFormatException.java
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/common/service/TokenRefreshService.java
  src/main/java/cherish/backend/common/util/.gitkeep
  src/main/java/cherish/backend/common/util/DurationShortFormUtils.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
  src/main/java/cherish/backend/member/dto/MemberLoginRequestDto.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/main/resources/application.yml
Labels: feature, member

#85 Refactor/83 add email verification
  src/main/java/cherish/backend/auth/jwt/JwtTokenProvider.java
  src/main/java/cherish/backend/common/exception/RedisKeyNotFoundException.java
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/common/service/TokenRefreshService.java
  src/main/java/cherish/backend/member/constant/Constants.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
  src/main/java/cherish/backend/member/email/service/AwsEmailService.java
  src/main/java/cherish/backend/member/email/service/GoogleEmailService.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/main/java/cherish/backend/test/TestRestController.java
  src/test/java/cherish/backend/member/controller/MemberControllerTest.java
Labels: refactor

#86 Refactor/82 refactor ItemLikeController.java
  src/main/java/cherish/backend/item/controller/ItemLikeController.java
  src/main/java/cherish/backend/item/dto/ItemLikeDto.java
  src/main/java/cherish/backend/item/dto/ItemLikeRequest.java
  src/main/java/cherish/backend/item/service/ItemLikeService.java
  src/test/java/cherish/backend/item/controller/ItemLikeControllerTest.java
  src/test/java/cherish/backend/item/service/ItemLikeServiceTest.java
Labels: refactor

#89 Item Like를 인증 기반으로 변경하고 query 수정
  src/main/java/cherish/backend/item/controller/ItemLikeController.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemLikeRepositoryImpl.java
  src/main/java/cherish/backend/item/service/ItemLikeService.java
Labels: bug

#93 Refactor/91 apply httponly cookie refresh token
  src/main/java/cherish/backend/auth/jwt/JwtConfig.java
  src/main/java/cherish/backend/auth/jwt/TokenInfo.java
  src/main/java/cherish/backend/auth/jwt/dto/TokenResponseDto.java
  src/main/java/cherish/backend/common/constant/CommonConstants.java
  src/main/java/cherish/backend/common/controller/TokenRefreshController.java
  src/main/java/cherish/backend/common/dto/RefreshTokenRequestDto.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
Labels: refactor

#95 Refactor/94 remove duplicate sql & fix bug
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/repository/MemberRepository.java
  src/main/java/cherish/backend/member/service/MemberService.java
Labels: bug, refactor

#96 상품 상세정보 api
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemInfoResponseDto.java
  src/main/java/cherish/backend/item/model/Item.java
  src/main/java/cherish/backend/item/repository/ItemCategoryRepository.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepository.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/java/cherish/backend/item/repository/ItemRepository.java
  src/main/java/cherish/backend/item/repository/ItemRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemRepositoryImpl.java
  src/main/java/cherish/backend/item/repository/ItemUrlRepository.java
  src/main/java/cherish/backend/item/service/ItemService.java
  src/test/java/cherish/backend/item/service/ItemInfoServiceTest.java
Labels: feature

#101 allowed methods 버그 수정
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
  src/main/java/cherish/backend/common/config/cors/CorsProperties.java
  src/main/resources/application.yml
Labels: bug

#103 feature: 큐레이션 컨트롤러 validation
  src/main/java/cherish/backend/curation/controller/PublicCurationController.java
  src/main/java/cherish/backend/curation/dto/CurationRequestParam.java
  src/main/java/cherish/backend/curation/dto/CurationResponseDto.java
  src/main/java/cherish/backend/curation/repository/CurationRepository.java
  src/main/java/cherish/backend/curation/service/CurationService.java
  src/test/java/cherish/backend/curation/controller/PublicCurationControllerTest.java
  src/test/java/cherish/backend/member/MemberTest.java
Labels: feature, curation

#98 Refactor/97 item response
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemInfoResponseDto.java
  src/main/java/cherish/backend/item/dto/ItemInfoViewDto.java
  src/main/java/cherish/backend/item/repository/ItemCategoryRepository.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepository.java
  src/main/java/cherish/backend/item/repository/ItemRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemRepositoryImpl.java
  src/main/java/cherish/backend/item/repository/ItemUrlRepository.java
  src/main/java/cherish/backend/item/service/ItemService.java
  src/test/java/cherish/backend/item/service/ItemInfoServiceTest.java
Labels: refactor

#106 refactor 필터링 조건
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemSearchCondition.java
  src/main/java/cherish/backend/item/dto/ItemSearchResponseDto.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/test/java/cherish/backend/item/controller/ItemInfoControllerTest.java
  src/test/java/cherish/backend/item/service/ItemInfoServiceTest.java
  src/test/java/cherish/backend/item/service/ItemSearchServiceTest.java
Labels: search, refactor

#111 Refactor/104 add change password
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/curation/dto/CurationRequestParam.java
  src/main/java/cherish/backend/member/constant/Constants.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/dto/ChangeInfoRequest.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/dto/MemberInfoResponse.java
  src/main/java/cherish/backend/member/dto/MemberLoginRequestDto.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/test/java/cherish/backend/member/MemberTest.java
  src/test/java/cherish/backend/member/controller/MemberControllerTest.java
  src/test/java/cherish/backend/member/service/MemberServiceUnitTest.java
Labels: refactor

#114 로그아웃 API 추가
  src/main/java/cherish/backend/auth/jwt/JwtTokenProvider.java
  src/main/java/cherish/backend/auth/jwt/config/JwtConfig.java
  src/main/java/cherish/backend/auth/jwt/config/JwtProperties.java
  src/main/java/cherish/backend/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/cherish/backend/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/cherish/backend/auth/jwt/util/TokenResolver.java
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
  src/main/java/cherish/backend/common/controller/TokenRefreshController.java
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
Labels: feature

#118 [refactor] search response에 liked 필드 추가
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemSearchResponseDto.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/java/cherish/backend/item/service/ItemService.java
  src/test/java/cherish/backend/item/service/ItemSearchServiceTest.java
Labels: search, refactor

#119 fix: 이메일 인증코드 형식 수정
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/member/email/service/AwsEmailService.java
  src/main/java/cherish/backend/member/email/service/EmailService.java
  src/main/java/cherish/backend/member/email/service/GoogleEmailService.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/test/java/cherish/backend/member/controller/MemberControllerTest.java
  src/test/java/cherish/backend/member/email/AwsEmailServiceTest.java
Labels: refactor

#121 [feature] main page API
  src/main/java/cherish/backend/item/controller/PublicRecommendItemController.java
  src/main/java/cherish/backend/item/dto/RecommendItemQueryDto.java
  src/main/java/cherish/backend/item/dto/RecommendItemResponseDto.java
  src/main/java/cherish/backend/item/model/Item.java
  src/main/java/cherish/backend/item/repository/ItemRepository.java
  src/main/java/cherish/backend/item/repository/RecommendItemRepository.java
  src/main/java/cherish/backend/item/service/RecommendItemService.java
Labels: feature

#123 [fix] search filter 동일 컬럼에 대한 필터링 조건 (situationName, gender) fix
  src/main/java/cherish/backend/item/controller/PublicItemController.java
  src/main/java/cherish/backend/item/dto/ItemSearchCondition.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/java/cherish/backend/item/service/ItemService.java
  src/main/resources/application.yml
Labels: bug, search

#125 Refactor/124 fix log config enable http2
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: refactor
