Repository Cherish-Gift/back-spring, pull requests merged in 2023-03, with the labels that each got.

#5 [common] gitignore에 generated 폴더 추가
  .gitignore
Labels: feature

#12 #11 vault 연결 설정 및 Hikari CP datasource 추가
  build.gradle
  src/main/java/cherish/backend/config/db/DataSourceConfig.java
  src/main/java/cherish/backend/config/db/SimpleHikariConfig.java
  src/main/java/cherish/backend/config/vault/VaultConfig.java
  src/main/java/cherish/backend/config/vault/VaultProperties.java
  src/main/resources/application.yml
Labels: bug, feature

#16 Feature/14 profile datasource
  src/main/java/cherish/backend/common/config/db/DataSourceConfig.java
  src/main/java/cherish/backend/common/config/db/SimpleHikariConfig.java
  src/main/java/cherish/backend/common/config/vault/VaultConfig.java
  src/main/java/cherish/backend/common/config/vault/VaultProperties.java
  src/main/resources/application.yml
Labels: feature

#19 [Feature] category entity
  src/main/java/cherish/backend/category/model/.gitkeep
  src/main/java/cherish/backend/category/model/Category.java
  src/main/java/cherish/backend/category/repository/.gitkeep
  src/main/java/cherish/backend/category/repository/CategoryRepository.java
  src/main/java/cherish/backend/common/model/BaseTimeEntity.java
  src/test/java/cherish/backend/category/model/CategoryTest.java
Labels: feature

#20 [logging] logback config 추가
  src/main/resources/logback-spring.xml
Labels: documentation, feature

#23 issue #22 ERD 반영 화면 설계상 부족한 필드와 RDS columns 생성
  build.gradle
  src/main/java/cherish/backend/auth/security/SecurityUser.java
  src/main/java/cherish/backend/board/model/MonthlyBoard.java
  src/main/java/cherish/backend/category/model/Mood.java
  src/main/java/cherish/backend/category/model/Situation.java
  src/main/java/cherish/backend/item/model/ItemCategory.java
  src/main/java/cherish/backend/item/model/ItemMood.java
  src/main/java/cherish/backend/item/model/ItemSituation.java
  src/main/java/cherish/backend/item/model/MonthlyBoardItem.java
  src/main/java/cherish/backend/item/model/enums/ItemType.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/model/enums/Gender.java
  src/main/java/cherish/backend/member/repository/MemberRepository.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/test/java/cherish/backend/category/model/CategoryTest.java
  src/test/java/cherish/backend/item/model/ItemTest.java
  src/test/java/cherish/backend/member/MemberTest.java
  src/test/resources/application.yml
Labels: feature

#24 issue #21 shutdown graceful option + test
  src/main/java/cherish/backend/test/TestRestController.java
  src/main/resources/application.yml
Labels: feature

#31 #27-ErrorResponse & test
  src/main/java/cherish/backend/common/dto/.gitkeep
  src/main/java/cherish/backend/common/dto/ErrorResponseDto.java
  src/main/java/cherish/backend/common/exception/.gitkeep
  src/main/java/cherish/backend/common/exception/GlobalExceptionHandler.java
  src/test/java/cherish/backend/common/exception/GlobalExceptionHandlerTest.java
Labels: feature

#30 feature/26 setup p6spy
  build.gradle
  src/main/java/cherish/backend/common/config/p6spy/P6spyConfig.java
  src/main/java/cherish/backend/common/config/p6spy/P6spyPrettyFormattingStrategy.java
  src/main/resources/application.yml
Labels: feature

#32 issue #28 redis connect & test
  build.gradle
  src/main/java/cherish/backend/common/config/redis/RedisConfig.java
  src/main/java/cherish/backend/common/config/redis/RedisProperties.java
  src/main/java/cherish/backend/common/service/.gitkeep
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/test/TestRestController.java
  src/main/resources/application.yml
  src/test/java/cherish/backend/common/service/RedisServiceTest.java
  src/test/resources/application.yml
Labels: feature

#37 Refactor/36 refactor 전체적인 구조 리팩토링
  build.gradle
  src/main/java/cherish/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/cherish/backend/auth/jwt/JwtTokenProvider.java
  src/main/java/cherish/backend/auth/jwt/TokenInfo.java
  src/main/java/cherish/backend/auth/security/CurrentUser.java
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
  src/main/java/cherish/backend/auth/security/SecurityUtil.java
  src/main/java/cherish/backend/board/model/MonthlyBoard.java
  src/main/java/cherish/backend/category/model/Category.java
  src/main/java/cherish/backend/common/aop/.gitkeep
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/common/constant/CommonConstants.java
  src/main/java/cherish/backend/common/exception/.gitkeep
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/item/model/Item.java
  src/main/java/cherish/backend/item/model/ItemUrl.java
  src/main/java/cherish/backend/item/model/enums/ItemType.java
  src/main/java/cherish/backend/member/constant/Constants.java
  src/main/java/cherish/backend/member/controller/EmailApiController.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/model/enums/Gender.java
  src/main/java/cherish/backend/member/model/enums/Role.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/main/java/cherish/backend/test/TestRestController.java
  src/main/resources/banner.txt
  src/test/java/cherish/backend/common/exception/GlobalExceptionHandlerTest.java
Labels: refactor

#39 Feature/#34 register email valid
  build.gradle
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
  src/main/java/cherish/backend/common/service/RedisService.java
  src/main/java/cherish/backend/member/controller/EmailApiController.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/dto/ChangeInfoRequest.java
  src/main/java/cherish/backend/member/dto/ChangePwdRequest.java
  src/main/java/cherish/backend/member/dto/MemberChangeRequest.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/dto/email/EmailCodeValidationRequest.java
  src/main/java/cherish/backend/member/dto/email/EmailRequest.java
  src/main/java/cherish/backend/member/email/EmailCode.java
  src/main/java/cherish/backend/member/email/EmailService.java
  src/main/java/cherish/backend/member/email/SendEmailService.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/repository/JobRepository.java
  src/main/java/cherish/backend/member/service/MemberService.java
  src/main/java/cherish/backend/test/TestRestController.java
  src/main/resources/application.yml
  src/test/java/cherish/backend/common/service/RedisServiceTest.java
  src/test/java/cherish/backend/member/controller/MemberControllerTest.java
  src/test/java/cherish/backend/member/email/SendEmailServiceTest.java
  src/test/java/cherish/backend/member/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: feature

#47 [refactor] ItemFilter querydsl refactoring, Item entity ItemUrl entity field update
  build.gradle
  settings.gradle
  src/main/java/cherish/backend/item/dto/.gitkeep
  src/main/java/cherish/backend/item/dto/AgeFilterCondition.java
  src/main/java/cherish/backend/item/dto/AgeFilterQueryDto.java
  src/main/java/cherish/backend/item/dto/ItemFilterCondition.java
  src/main/java/cherish/backend/item/dto/ItemFilterQueryDto.java
  src/main/java/cherish/backend/item/model/Item.java
  src/main/java/cherish/backend/item/model/ItemUrl.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepository.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryCustom.java
  src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
  src/main/java/cherish/backend/member/constant/.gitkeep
  src/test/java/cherish/backend/item/model/ItemFilterTest.java
  src/test/java/cherish/backend/member/MemberTest.java
  src/test/resources/application.yml
Labels: refactor

#50 findItemFilterByNameAndFilterId 메소드 원복
  src/main/java/cherish/backend/item/repository/ItemFilterRepository.java
Labels: bug

#53 Refactor/#52 public controller
  src/main/java/cherish/backend/auth/security/SecurityConfig.java
  src/main/java/cherish/backend/member/constant/Constants.java
  src/main/java/cherish/backend/member/controller/EmailApiController.java
  src/main/java/cherish/backend/member/controller/MemberController.java
  src/main/java/cherish/backend/member/controller/PublicMemberController.java
  src/main/java/cherish/backend/member/dto/ChangeInfoRequest.java
  src/main/java/cherish/backend/member/dto/ChangePwdRequest.java
  src/main/java/cherish/backend/member/dto/MemberFormDto.java
  src/main/java/cherish/backend/member/dto/MemberInfoResponse.java
  src/main/java/cherish/backend/member/dto/MemberLoginRequestDto.java
  src/main/java/cherish/backend/member/dto/email/EmailCodeValidationRequest.java
  src/main/java/cherish/backend/member/model/Member.java
  src/main/java/cherish/backend/member/service/MemberService.java
Labels: feature

#61 #59 add type error
  src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
Labels: feature
